"""
Script Exporter - Converts the structured test cases produced by
test_generator.py into runnable test-script skeletons in popular
testing frameworks. Pure transformer over existing JSON output;
the explainability metadata (source_trigger) is preserved as
docstrings/comments so traceability survives in code form.
"""
import json
import re
from datetime import datetime
from typing import List


SUPPORTED_FRAMEWORKS = ("pytest", "playwright", "cypress", "postman", "cucumber")


def _safe_name(text: str) -> str:
    """Convert a free-text title into a python/js identifier."""
    s = re.sub(r"[^a-zA-Z0-9]+", "_", (text or "test").strip().lower())
    s = re.sub(r"_+", "_", s).strip("_")
    if not s:
        s = "test"
    if s[0].isdigit():
        s = "tc_" + s
    return s[:80]


def export_script(framework: str, story: str, test_cases: List[dict]) -> tuple[str, str, str]:
    """
    Returns (filename, mimetype, body) for the requested framework.
    """
    framework = (framework or "pytest").lower()
    if framework not in SUPPORTED_FRAMEWORKS:
        raise ValueError(
            f"Unsupported framework '{framework}'. "
            f"Supported: {', '.join(SUPPORTED_FRAMEWORKS)}"
        )

    if framework == "pytest":
        return "test_testcraft.py", "text/x-python", _to_pytest(story, test_cases)
    if framework == "playwright":
        return "testcraft.spec.js", "text/javascript", _to_playwright(story, test_cases)
    if framework == "cypress":
        return "testcraft.cy.js", "text/javascript", _to_cypress(story, test_cases)
    if framework == "postman":
        return "testcraft.postman_collection.json", "application/json", _to_postman(story, test_cases)
    if framework == "cucumber":
        return "testcraft.feature", "text/plain", _to_cucumber(story, test_cases)


# ─── Pytest (Selenium-style) ──────────────────────────────────────
def _to_pytest(story: str, cases: List[dict]) -> str:
    header = f'''"""
Auto-generated by TestCraft on {datetime.now().strftime('%Y-%m-%d %H:%M')}.
Source user story:
    {story}

Each test below preserves the TestCraft `source_trigger` so the
reasoning behind its existence remains traceable in code.
"""
import pytest


@pytest.fixture
def driver():
    # TODO: replace with your real driver/setup (Selenium, Requests, etc.)
    yield None
'''
    body = []
    seen = set()
    for tc in cases:
        name = f"test_{_safe_name(tc.get('title') or tc.get('id') or 'case')}"
        if name in seen:
            name = name + "_" + (tc.get("id") or "x").lower().replace("-", "_")
        seen.add(name)

        preconds = tc.get("preconditions") or []
        steps = tc.get("steps") or []
        expected = tc.get("expected_results") or []
        priority = tc.get("priority")
        priority_marker = f"\n@pytest.mark.priority({priority})" if priority else ""

        body.append(f'''
{priority_marker}
def {name}(driver):
    """
    [{tc.get("id", "")}] {tc.get("title", "")}
    Type:        {tc.get("type", "")}
    Category:    {tc.get("category", "")}
    Source:      {tc.get("source_trigger", "")}
    """
    # ── Preconditions ──
{_lines_as_comments(preconds, indent="    ")}

    # ── Steps ──
{_lines_as_pytest_steps(steps)}

    # ── Expected Results ──
{_lines_as_assertions(expected)}
'''.rstrip())
    return header + "\n" + "\n".join(body) + "\n"


def _lines_as_comments(items, indent="    "):
    if not items:
        return f"{indent}# (none)"
    return "\n".join(f"{indent}# - {x}" for x in items)


def _lines_as_pytest_steps(steps):
    if not steps:
        return "    pass  # TODO: implement"
    out = []
    for i, s in enumerate(steps, 1):
        out.append(f"    # Step {i}: {s}")
        out.append(f"    pass  # TODO: implement step {i}")
    return "\n".join(out)


def _lines_as_assertions(expected):
    if not expected:
        return "    assert True  # TODO: replace with real assertion"
    out = []
    for e in expected:
        safe = e.replace('"', '\\"')
        out.append(f'    # Expected: {e}')
        out.append(f'    assert True, "Expected: {safe}"')
    return "\n".join(out)


# ─── Playwright ───────────────────────────────────────────────────
def _to_playwright(story: str, cases: List[dict]) -> str:
    header = f"""// Auto-generated by TestCraft on {datetime.now().strftime('%Y-%m-%d %H:%M')}.
// Source user story:
//   {story}
//
// Each test preserves the TestCraft source_trigger as a comment.
const {{ test, expect }} = require('@playwright/test');

test.describe('TestCraft generated suite', () => {{
"""
    body_parts = []
    for tc in cases:
        name = (tc.get("title") or tc.get("id") or "case").replace("'", "\\'")
        steps = tc.get("steps") or []
        expected = tc.get("expected_results") or []
        prio = tc.get("priority")
        prio_tag = f" [P{prio}]" if prio else ""
        body_parts.append(
            f"  // [{tc.get('id','')}]{prio_tag} type={tc.get('type','')} "
            f"category={tc.get('category','')}\n"
            f"  // source: {tc.get('source_trigger','')}\n"
            f"  test('{name}', async ({{ page }}) => {{\n"
            + "\n".join(f"    // Step {i+1}: {s}\n    // TODO" for i, s in enumerate(steps))
            + ("\n" if steps else "")
            + "\n".join(f"    // Expect: {e}\n    expect(true).toBeTruthy();" for e in expected)
            + ("\n" if expected else "")
            + "  });"
        )
    return header + "\n\n".join(body_parts) + "\n});\n"


# ─── Cypress ─────────────────────────────────────────────────────
def _to_cypress(story: str, cases: List[dict]) -> str:
    header = f"""// Auto-generated by TestCraft on {datetime.now().strftime('%Y-%m-%d %H:%M')}.
// Source user story:
//   {story}

describe('TestCraft generated suite', () => {{
"""
    body_parts = []
    for tc in cases:
        name = (tc.get("title") or tc.get("id") or "case").replace("'", "\\'")
        steps = tc.get("steps") or []
        expected = tc.get("expected_results") or []
        prio = tc.get("priority")
        prio_tag = f" [P{prio}]" if prio else ""
        body_parts.append(
            f"  // [{tc.get('id','')}]{prio_tag} {tc.get('source_trigger','')}\n"
            f"  it('{name}', () => {{\n"
            + "\n".join(f"    // Step {i+1}: {s}\n    // TODO" for i, s in enumerate(steps))
            + ("\n" if steps else "")
            + "\n".join(f"    // Expect: {e}\n    cy.wrap(true).should('be.true');" for e in expected)
            + ("\n" if expected else "")
            + "  });"
        )
    return header + "\n\n".join(body_parts) + "\n});\n"


# ─── Postman collection ──────────────────────────────────────────
def _to_postman(story: str, cases: List[dict]) -> str:
    items = []
    for tc in cases:
        items.append({
            "name": f"[{tc.get('id','')}] {tc.get('title','')}",
            "event": [{
                "listen": "test",
                "script": {
                    "exec": [
                        f"// Source: {tc.get('source_trigger','')}",
                        *[f"// Expect: {e}" for e in (tc.get("expected_results") or [])],
                        "pm.test('TODO: replace with real assertion', function () {",
                        "  pm.expect(true).to.eql(true);",
                        "});",
                    ],
                    "type": "text/javascript",
                },
            }],
            "request": {
                "method": "GET",
                "header": [],
                "url": {"raw": "https://example.com", "protocol": "https", "host": ["example", "com"]},
                "description": (
                    f"Type: {tc.get('type','')}\n"
                    f"Category: {tc.get('category','')}\n\n"
                    "Preconditions:\n" + "\n".join(f"- {p}" for p in (tc.get("preconditions") or [])) +
                    "\n\nSteps:\n" + "\n".join(f"{i+1}. {s}" for i, s in enumerate(tc.get("steps") or []))
                ),
            },
        })

    collection = {
        "info": {
            "name": "TestCraft Generated Collection",
            "description": f"Generated on {datetime.now().isoformat()}\n\nUser story:\n{story}",
            "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json",
        },
        "item": items,
    }
    return json.dumps(collection, indent=2)


# ─── Cucumber .feature ───────────────────────────────────────────
def _to_cucumber(story: str, cases: List[dict]) -> str:
    out = [
        f"# Auto-generated by TestCraft on {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"# Source story: {story}",
        "",
        "Feature: TestCraft generated suite",
        "",
    ]
    for tc in cases:
        out.append(f"  # [{tc.get('id','')}] {tc.get('source_trigger','')}")
        out.append(f"  Scenario: {tc.get('title','')}")
        for p in (tc.get("preconditions") or []):
            out.append(f"    Given {p}")
        for i, s in enumerate(tc.get("steps") or []):
            kw = "When" if i == 0 else "And"
            out.append(f"    {kw} {s}")
        for j, e in enumerate(tc.get("expected_results") or []):
            kw = "Then" if j == 0 else "And"
            out.append(f"    {kw} {e}")
        out.append("")
    return "\n".join(out)
